# Generated by Django 5.2.7 on 2026-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_displaystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
