# Generated by Django 5.2.7 on 2026-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_equipmenttype_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('Receiver', 'Receiver'), ('Accessory', 'Accessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EchoSounder', 'EchoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], default='Receiver', max_length=20),
        ),
    ]
