# Generated by Django 5.2.7 on 2026-04-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_equipmenttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Receiver', 'Receiver'), ('Accessory', 'Accessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EchoSounder', 'EchoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], max_length=50),
        ),
    ]
