# Generated by Django 5.2.7 on 2026-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_tool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('overdue', 'Overdue'), ('fully-paid', 'Fully Paid'), ('credit', 'Credit')], default='ongoing', max_length=20, verbose_name='Payment Status'),
        ),
    ]
