# Generated by Django 5.2.7 on 2026-05-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='document_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], default='quotation', max_length=20),
        ),
    ]
