# Generated by Django 5.2.7 on 2026-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_quotation_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Import Expiry Date'),
        ),
    ]
