# Generated by Django 5.2.7 on 2026-05-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
