# Generated by Django 5.2.7 on 2026-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_quotation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3),
        ),
    ]
