# Generated by Django 5.2.7 on 2026-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_quotation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3),
        ),
    ]
