# Generated by Django 5.2.7 on 2026-05-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_sale_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original USD Amount'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exchange Rate NGN per USD'),
        ),
    ]
