# Generated by Django 5.2.7 on 2026-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_invoice_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exchange Rate NGN per USD'),
        ),
        migrations.AddField(
            model_name='sale',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original USD Amount'),
        ),
    ]
