# Generated by Django 5.2.7 on 2026-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_sale_exchange_rate_sale_usd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
