# Generated by Django 5.2.7 on 2026-05-27 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_invoice_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('serial_mismatch', 'Serial Number Mismatch'), ('wrong_category', 'Wrong Category'), ('wrong_cost', 'Wrong Cost'), ('wrong_quantity', 'Wrong Quantity'), ('damaged', 'Damaged Item'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_flags', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='inventory.tool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
