# Generated by Django 5.2.7 on 2026-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_inventoryflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchserial',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='batchserial',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
