# Generated by Django 5.2.7 on 2026-09-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_batchserial_month_batchserial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='low_stock_notified',
            field=models.BooleanField(default=False, verbose_name='Low Stock Alert Sent'),
        ),
    ]
