# Generated by Django 5.2.7 on 2026-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_tool_low_stock_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Delivery Charge'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Shipping Charge'),
        ),
    ]
